server:
  port: 8080 #puerto donde corre tu API

spring:
  datasource:
    url: jdbc:mysql://localhost:3377/agenda_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ..MalTin2022
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Hibernate valida, no crea tablas (Flyway las crea)
    show-sql: true # Muestra queries en consola
    properties:
      hibernate:
        format-sql: true # Para ver las queries más legibles

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration # Carpeta de migraciones

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
