server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    # url: jdbc:mysql://db:3306/agenda_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3377/agenda_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC #casa
    # url: jdbc:mysql://localhost:3311/agenda_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC #trabajo
    # username: agenda_user
    username: root # casa y trabajo
    # password: secret # docker
    password: ..MalTin2022 #casa
    # password: ..Admin2025 #trabajo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Logs de debugging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.agenda.agenda_inteligente: DEBUG
